---
theme: "polymer"

baseurl: "https://golangmontreal.org"

paginate: 10

MetaDataFormat: "yaml"
DefaultContentLang: en

menu:
  - main
  - footer

Multilingual:
  en:
    weight: 1

    title: "Golang Montréal - #gomtl"
    languageCode: "en-CA"

    copyright: "(ɔ) 2015 Copyleft. The #gomtl team."

  fr:
    weight: 2

    title: "Golang Montréal - #gomtl"
    languageCode: "fr-CA"

    copyright: "(ɔ) 2015 L'équipe #gomtl. Tous droits renversés."

params:
  # Number of articles in the "Latest news" section on the front page.
  homepage_news: 3
  author: "gomtl team"
  profile: "images/gomtl-logo-512.png"
  linkedin: "8460965"
  twitter: "GolangMontreal"
  youtube: "channel/UCEse7ZihAhMMMFGesx8dJjg"
  github: "gomtl"
  facebook: "GolangMontreal"
  meetup: "fr-FR/GolangMontreal"
  slack: "https://bit.ly/go-slack-signup"
  googleAnalyticsUserID: "UA-72488186-1"
  # See http://www.meetup.com/fr-FR/meetup_api/buttons/
  meetupButtonBaseURL: http://www.meetup.com/GolangMontreal

permalinks:
  post: "/:year/:month/:day/:slug/"
